theme: jekyll-theme-modernist
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Analyzing balance between latency versus accuracy of remote robot control with lossy image preprocessing
description: Project for UCLA ECEM202A/CSM213A (Fall 2021)
